import React, { useEffect, useState } from 'react';
import { ShieldCheck, Users, ScrollText, RefreshCw } from 'lucide-react';
import { api } from '../services/api.ts';
import { useAuth } from '../context/AuthContext.tsx';

export const AdminView: React.FC = () => { const {user}=useAuth(); const [tab,setTab]=useState<'employees'|'audit'>('employees'); const [employees,setEmployees]=useState<any[]>([]); const [logs,setLogs]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{if(user?.role!=='owner'){setLoading(false);return;} Promise.all([api.getEmployees(),api.getAuditLogs()]).then(([e,l])=>{setEmployees(e);setLogs(l)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[user]);
 if(user?.role!=='owner') return <div className="bm-card p-10 text-center"><ShieldCheck className="w-8 h-8 mx-auto text-slate-400"/><h2 className="font-semibold text-slate-900 mt-3">Owner access required</h2><p className="text-sm text-slate-500 mt-1">Employees and audit history contain administrative information.</p></div>;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Administration</h1><p className="text-sm text-slate-500 mt-1">Manage people and review important business actions.</p></div><div className="flex gap-2"><button onClick={()=>setTab('employees')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${tab==='employees'?'bg-slate-900 text-white':'bg-white border border-slate-200 text-slate-600'}`}><Users className="inline w-4 h-4 mr-2"/>Employees</button><button onClick={()=>setTab('audit')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${tab==='audit'?'bg-slate-900 text-white':'bg-white border border-slate-200 text-slate-600'}`}><ScrollText className="inline w-4 h-4 mr-2"/>Audit logs</button></div>{loading?<div className="bm-card p-10 text-center text-sm text-slate-500">Loading administrative records…</div>:error?<div className="bm-card p-10 text-center text-sm text-rose-600">{error}</div>:tab==='employees'?<div className="bm-card overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="text-left px-5 py-3">Person</th><th className="text-left px-5 py-3">Role</th><th className="text-left px-5 py-3">Job title</th><th className="text-left px-5 py-3">Joined</th></tr></thead><tbody>{employees.map(e=><tr className="border-t border-slate-100" key={e.id}><td className="px-5 py-4"><div className="font-semibold text-slate-900">{e.name}</div><div className="text-xs text-slate-500">{e.email}</div></td><td className="px-5 py-4"><span className="px-2 py-1 rounded-full bg-slate-100 text-slate-700 text-xs font-semibold uppercase">{e.role}</span></td><td className="px-5 py-4 text-slate-600">{e.job_title||'—'}</td><td className="px-5 py-4 text-slate-600">{new Date(e.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<div className="bm-card overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="text-left px-5 py-3">Action</th><th className="text-left px-5 py-3">Details</th><th className="text-left px-5 py-3">Time</th></tr></thead><tbody>{logs.map(l=><tr className="border-t border-slate-100" key={l.id}><td className="px-5 py-4 font-semibold text-slate-900">{l.action}</td><td className="px-5 py-4 text-slate-600">{l.details}</td><td className="px-5 py-4 text-slate-500 whitespace-nowrap">{new Date(l.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</div>;
};
