import React, { useEffect, useMemo, useState } from 'react';
import { Users, Search, UserRound, Mail, Phone, MapPin } from 'lucide-react';
import { api } from '../services/api.ts';

export const CustomersView: React.FC = () => {
  const [customers,setCustomers]=useState<any[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{api.getCustomers().then(setCustomers).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const rows=useMemo(()=>customers.filter(c=>[c.name,c.email,c.phone,c.location].join(' ').toLowerCase().includes(q.toLowerCase())),[customers,q]);
  const total=customers.reduce((n,c)=>n+(c.total_spent||0),0);
  return <div className="space-y-6">
    <div><div className="flex items-center gap-2"><Users className="w-5 h-5 text-slate-700"/><h1 className="text-2xl font-bold text-slate-900">Customers</h1></div><p className="text-sm text-slate-500 mt-1">Understand customer activity and commercial value from recorded sales.</p></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bm-card p-5"><div className="bm-label">Active records</div><div className="text-2xl font-bold text-slate-900 mt-1">{customers.length}</div></div><div className="bm-card p-5"><div className="bm-label">Total recorded spend</div><div className="text-2xl font-bold text-slate-900 mt-1">৳{total.toLocaleString()}</div></div><div className="bm-card p-5"><div className="bm-label">Search results</div><div className="text-2xl font-bold text-slate-900 mt-1">{rows.length}</div></div></div>
    <div className="bm-card overflow-hidden"><div className="p-4 border-b border-slate-200"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers" className="w-full pl-9 pr-3 py-2.5 rounded-lg border border-slate-200 text-sm outline-none focus:ring-2 focus:ring-slate-200"/></div></div>
      {loading?<div className="p-10 text-center text-sm text-slate-500">Loading customer records…</div>:error?<div className="p-10 text-center text-sm text-rose-600">{error}</div>:rows.length===0?<div className="p-10 text-center text-sm text-slate-500">No customer records match your search.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="text-left px-5 py-3">Customer</th><th className="text-left px-5 py-3">Contact</th><th className="text-left px-5 py-3">Location</th><th className="text-right px-5 py-3">Recorded spend</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t border-slate-100"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-slate-100 flex items-center justify-center"><UserRound className="w-4 h-4 text-slate-500"/></div><div><div className="font-semibold text-slate-900">{c.name}</div><div className="text-xs text-slate-500">{c.id}</div></div></div></td><td className="px-5 py-4 text-slate-600"><div className="flex gap-2 items-center"><Mail className="w-3.5 h-3.5"/>{c.email}</div><div className="flex gap-2 items-center mt-1"><Phone className="w-3.5 h-3.5"/>{c.phone}</div></td><td className="px-5 py-4 text-slate-600"><div className="flex gap-2 items-center"><MapPin className="w-3.5 h-3.5"/>{c.location}</div></td><td className="px-5 py-4 text-right font-semibold text-slate-900">৳{Number(c.total_spent||0).toLocaleString()}</td></tr>)}</tbody></table></div>}
    </div>
  </div>;
};
